# Generated by Django 4.0 on 2022-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
