# Generated by Django 4.0 on 2022-01-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studApp', '0002_alter_studentinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademic',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentAcademic', to='studApp.studentinfo'),
        ),
    ]
